version: '2'

services:

### Applications Code Container #############################

    applications:
        image: tianon/true
        volumes:
            - $APPLICATION_VOLUME_PATH:/home/bitrix/www


### Workspace Utilities Container ###########################

    workspace:
        restart: always
        build:
            context: ./workspace
            args:
                - TZ=$TZ
                - PUID=1000
                - PGID=1000
                - INSTALL_MEMCACHED=true
                - INSTALL_EXIF=false
                - INSTALL_OPCACHE=true
                - INSTALL_MYSQLI=true
                - INSTALL_INTL=false
                - INSTALL_XDEBUG=false
                - INSTALL_BLACKFIRE=false
                - INSTALL_WORKSPACE_SSH=false
                - COMPOSER_GLOBAL_INSTALL=true
                - INSTALL_NODE=true
                - NODE_VERSION=stable
                - INSTALL_YARN=true
                - YARN_VERSION=latest
        volumes_from:
            - applications
        networks:
            - default
        tty: true


### PHP-FPM Container #######################################

    php-fpm:
        restart: always
        build:
            context: ./php-fpm
            args:
                - INSTALL_XDEBUG=$INSTALL_XDEBUG
                - INSTALL_SOAP=true
                - INSTALL_ZIP_ARCHIVE=true
                - INSTALL_BCMATH=false
                - INSTALL_PHPREDIS=false
                - INSTALL_MEMCACHED=true
                - INSTALL_OPCACHE=true
                - INSTALL_EXIF=true
            dockerfile: Dockerfile-71
        environment:
            - PHP_IDE_CONFIG=serverName=$VIRTUAL_HOST_MAIN
        volumes_from:
            - applications
        expose:
            - "9000"
        links:
            - workspace
            - redis
        extra_hosts:
            - "dockerhost:$COMPOSE_DOCKER_HOST"
        networks:
            - default


### Nginx Server Container ##################################

    nginx:
        restart: always
        build:
            context: ./nginx
        volumes_from:
            - applications
        volumes:
            - ./nginx/bx:/etc/nginx/bx
            - ./nginx/certs:/etc/nginx/ssl
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/snippets:/etc/nginx/snippets
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - nginx_logs:/var/log/nginx
        links:
            - php-fpm
        environment:
            - VIRTUAL_HOST=$VIRTUAL_HOST


### Memcached Container #####################################

    memcached:
        restart: always
        build: ./memcached
        volumes:
            - memcached:/var/lib/memcached
        ports:
            - "11211:11211"
        links:
            - php-fpm


### Volumes Setup ###########################################

volumes:
    memcached:
        driver: "local"
